# Generated by Django 3.2.7 on 2021-11-13 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_market', '0005_auto_20211113_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockportfolio',
            name='earnt',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='net',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='spent',
        ),
        migrations.CreateModel(
            name='StockFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnt', models.FloatField(default=0)),
                ('spent', models.FloatField(default=0)),
                ('net', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_market.stockfolio'),
        ),
    ]
