# Generated by Django 3.2.7 on 2021-11-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0007_alter_stockportfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolio',
            name='action',
            field=models.CharField(default='', max_length=10),
        ),
    ]
