# Generated by Django 3.2.7 on 2021-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0008_stockportfolio_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolio',
            name='cur_price',
            field=models.FloatField(default=0),
        ),
    ]
