# Generated by Django 3.2.7 on 2021-11-13 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0009_stockportfolio_cur_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolio',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
