# Generated by Django 3.2.7 on 2021-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0010_stockportfolio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolio',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
